# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: ruby:2

stages:
  - syntax
  - lint
  - spec

before_script:
  - bundle install --gemfile=ci/Gemfile

syntax:manifests:
  stage: syntax
  script:
    - BUNDLE_GEMFILE=ci/Gemfile bundle exec rake --rakefile ci/rakefile_syntax syntax:manifests

syntax:templates:
  stage: syntax
  script:
    - BUNDLE_GEMFILE=ci/Gemfile bundle exec rake --rakefile ci/rakefile_syntax syntax:templates

syntax:hiera:
  stage: syntax
  script:
    - BUNDLE_GEMFILE=ci/Gemfile bundle exec rake --rakefile ci/rakefile_syntax syntax:hiera

lint:
  stage: lint
  script:
    - BUNDLE_GEMFILE=ci/Gemfile bundle exec rake --rakefile ci/rakefile_lint lint

spec:
  stage: spec
  script:
    - BUNDLE_GEMFILE=ci/Gemfile bundle exec rake spec
